{% set name = "secondarycoolantprops" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a40d5700d5966158a54a3c409553c6650dd42422bc996d9d2d65be0d9252c2a

build:
  entry_points:
    - scprop=scp.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - scp
    - pip
  run:
    - python >=3.8
    - click

test:
  imports:
    - scp
  commands:
    - pip check
    - scprop --help
  requires:
    - pip

about:
  home: https://github.com/mitchute/SecondaryCoolantProps
  summary: A collection of secondary coolant fluid property functions and classes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wouterpeere
